name: OpenWrt-CI

on:
  workflow_dispatch:
    
jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -qq install -y p7zip p7zip-full zip unzip gzip xz-utils pigz zstd subversion git curl
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h
      
      - name: make dir
        run: |
          mkdir /opt/kernel

      - name: upload files
        run: |
          cd /opt/kernel
          curl -LJO https://github.com/doushang/op-test/releases/download/0.1/boot-5.18.14-flippy-75+.tar.gz
          curl -LJO https://github.com/doushang/op-test/releases/download/0.1/dtb-rockchip-5.18.14-flippy-75+.tar.gz
          curl -LJO https://github.com/doushang/op-test/releases/download/0.1/modules-5.18.14-flippy-75+.tar.gz

      - name: init Lede
        run: |
          cd /opt
          git clone https://github.com/unifreq/openwrt_packit

      - name: upload openwrt-armvirt-64-default-rootfs.tar.gz
        run: |
          cd /opt/openwrt_packit
          curl -LJO https://github.com/doushang/op-test/releases/download/0.1/openwrt-armvirt-64-default-rootfs.tar.gz


      - name: ./mk_xxx.sh
        run: |
          cd /opt/openwrt_packit
          sudo ./mk_rk3568_r68s.sh

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: /opt/openwrt_packit/output/      
        
      - name: Upload OpenWrt Firmware to Release
        uses: ncipollo/release-action@v1
        with:
          tag: openwrt_armvirt_v8_${{ env.PACKAGED_OUTPUTDATE }}
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          token: ${{ secrets.YOURTOKEN }}
          body: |
            This is OpenWrt firmware for Phicomm N1
            * Firmware information
            Default IP: 192.168.1.1
            Default username: root
            Default password: password
